services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,iam,logs
      - LAMBDA_EXECUTOR=local
      - AWS_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - common_network

networks:
  common_network:
    driver: bridge

volumes:
  localstack_data:
